### PR TITLE
Only allow wildcards which form an entire path segment.

### PR DESCRIPTION
**Pull request by alex**
No weird sub-wildcards

### CODE REVIEW

**Comment by hynek** [comment]
Were there any changes to RFCs or something?  I can’t imagine I’ve implemented that out of boredom. 🤔

**Comment by alex** [comment]
Not AFAIK, browsers have been implementing this behavior for forever.

**Comment by alex** [comment]
Ok, looking at the RFC, it's listed as "may": https://tools.ietf.org/html/rfc6125#section-6.4.3

however, no other implementations actually do it that way; browsers don't, we're fixing it in cpython (https://github.com/python/cpython/pull/937), golang doesn't, etc.

**Comment by alex** [comment]
OpenSSL's hostname matcher has a flag for this `X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS`; but it's off by default.

**Comment by hynek** [comment]
Hm, so it’s kind of a stricter interpretation of the RFC.  I wonder how much of backward-compatibility issue this is.  Technically we’s have to add a warning for a year.

**Comment by alex** [comment]
Both Chrome and Firefox already have this behavior, which by itself severely limits the possibility of breaking anything in the real world.

**Comment by tiran** [comment]
I'm +1 for the change.

NSS and Firefox still seem to support substring wildcards: https://hg.mozilla.org/mozilla-central/file/tip/security/nss/lib/certdb/certdb.c#l1354

OpenSSL has substring matching enabled by default, too. The feature can be disabled with ```X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS ```, see
https://wiki.openssl.org/index.php/Manual:X509_check_host(3)

**Comment by alex** [comment]
Also I just confirmed that issuing a cert with a partial wildcard is a BR violation

**Pull request merged**
